config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: 'log_in'
  get "logout", to: "sessions#destroy"
  post "logout", to: "sessions#destroy" 
  get "profile", to: "users#profile"
  get "update-profile", to: "registrations#edit"
  patch "update-profile", to: "registrations#update"

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageUploader::Attachment(:image)
  #validates_presence_of :image_data 
 
  belongs_to :user
  has_many :likes
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
include ImageUploader::Attachment(:image)
has_secure_password
  has_many :posts
  has_many :comments
  has_many :likes
validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Invalid email" }
validates_presence_of :first_name, :last_name, :date_of_birth
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in.." if Current.user.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    #redirect_to posts_path
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username, :password, :email, :password_confirmation, :image, :first_name, :last_name, :date_of_birth))

    session[:user_id] = @user.id
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account created!"
    else
      render :new
    end
  end

  def edit
    @current_user = Current.user
  end

  def update 
    if Current.user.update(username: params[:user][:username], first_name: params[:user][:first_name], last_name: params[:user][:last_name], email: params[:user][:email], date_of_birth: params[:user][:date_of_birth])
      redirect_to root_path, notice: "Account updated!"
    else
      render :edit
      flash[:notice] = "There was a problem updating your details. Try again."
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:username])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Log In Success!"
    else
      flash.now[:alert] = "Invalid details."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = Current.user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_avatar(user_image)
    if user_image == nil
      'avatars/default_avatar.jpeg'
    else
      user_image
    end
  end

  def format_birthday(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finstagram</title>
    <%= csrf_meta_tags %>

   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('branding/favicon.png') %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notices' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script>
   $(function() {
      $('.toast').toast('show');
   });
  </script>
  </body>
  
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <p><%= post.caption %></p>
  <p><%= image_tag post.image_url %></p>
<% end %>

app/views/posts/new.html.erb
<!--
<%= form_for @post do |form| %>
  <%= form.label :caption %>
  <%= form.text_area :caption %>

  <%= form.label :image %>
  <%= image_tag form.object.image_url if form.object.cached_image_data %>
  <%= form.hidden_field :image, value: form.object.cached_image_data %>
  <%= form.file_field :image , :class => 'form-control', :type => 'file' %>

  <%= form.submit "Submit" %>
<% end %>
-->
<%= form_for @post do |form| %>
      <%= form.label :caption %>
      <%= form.text_area :caption %>
      <%= form.hidden_field :image%>
      <%= form.file_field :image %>
      <%= form.submit %>
 <% end %>
 
<!--
 <form action="/post/new" method="post" enctype="multipart/form-data">
  <input name="photo[image]" type="hidden" value="<%= @post.cached_image_data %>" />
  <input name="photo[image] "type="file" />
  <input type="submit" value="Create" />
</form>
-->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light" id="navbar">
<div class="container-fluid">
  <a class="navbar-brand" id="navbar-logo-banner" href="/">Finstagram</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="nav navbar-right">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if Current.user %>
      <a class="nav-link nav-user-name " href="<%= profile_path %>" id="profileLink" role="button">
         <%= image_tag default_avatar(Current.user.image_url), :style =>  'width: 35px;', :class => 'nav-avatar'%>
         <%= Current.user.username%>
       </a>
       </ul>
     </li>
   </ul>  
 </ul>
 <li>
 <%= link_to 'New Post', new_post_path, class: 'btn nav-buttons btn-sm btn-outline-light' %>
 <%= link_to 'Edit Profile', update_profile_path, class: 'btn nav-buttons btn-sm btn-outline-light' %>
 <%= link_to 'Logout', logout_path, class: 'btn nav-buttons btn-sm btn-outline-light' %></li>
      <% else %>
       <%= link_to 'Login', sign_in_path, class: 'btn nav-buttons btn-sm btn-outline-light' %>
      <%= link_to 'Sign Up', sign_up_path, class: 'btn nav-buttons btn-sm btn-outline-light' %>
      <% end %>
    </div>
  </div>
</div>
</nav>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true" style="position: absolute">
  <div class="d-flex">
    <div class="toast-body">
      <%= notice %>
   </div>
    <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>
<% end %>
<% if alert %>
  <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true" style="position: absolute">
  <div class="d-flex">
    <div class="toast-body">
      <%= alert %>
   </div>
    <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>
<% end %>

app/views/users/profile.html.erb
<div class="mt-5 row align-items-start">
  <div class="col-5">
    <div class="container d-flex justify-content-center align-items-center" >
        <div class="card" id="profile-card">
            <div class="user text-center">
                <div class="profile mt-3"> <%= image_tag default_avatar(Current.user.image_url), :style =>  'width: 80px;', :class => "rounded-circle"%> </div>
            </div>
            <div class="mt-3 text-center">
                <h4 class="mb-0"><%=@user.username %> </h4> <span class="text-muted d-block mb-2"><%= format_birthday(@user.date_of_birth) %></span> <button class="btn btn-primary btn-sm follow">Add Friend</button>
                <div class="d-flex justify-content-center align-items-center mt-4 px-4">
                    <div class="stats">
                        <h6 class="mb-0">Friends</h6> <span>0</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<main class="form-signin">
<h1>Welcome to Finstagram</h1>
</main>